name: CI

on:
  push:
    branches: [ '*' ]
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu
    - name: Cache Konan
      uses: ./.github/actions/cache-konan
    - name: Cache Gradle
      uses: ./.github/actions/cache-gradle
    - name: Run all tests
      run: ./gradlew check --stacktrace --info
      shell: bash

  assemble:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run assemble
        run: ./gradlew assemble --stacktrace
        shell: bash

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run format check
        run: ./gradlew ktlintCheck --stacktrace
        shell: bash

  deploy-snapshot:
    needs: [ test, assemble, lint ]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSPHRASE }}
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu
    - name: Cache Konan
      uses: ./.github/actions/cache-konan
    - name: Cache Gradle
      uses: ./.github/actions/cache-gradle
    - name: Deploy snapshot
      run: ./gradlew publishAllPublicationsToMavenCentralRepository -Dsnapshot=true --stacktrace
      shell: bash

  deploy-release:
    needs: [ test, assemble, lint ]
    if: startsWith(github.ref, 'refs/tags')
    runs-on: macos-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSPHRASE }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu
    - name: Cache Konan
      uses: ./.github/actions/cache-konan
    - name: Cache Gradle
      uses: ./.github/actions/cache-gradle
    - name: Deploy release
      run: ./gradlew publishToMavenCentral --stacktrace --no-configuration-cache
      shell: bash
