name: Test
on:
  schedule:
    - cron: '0 8 * * 1'
  push:
    branches-ignore: [ main ]
    paths-ignore:
      - '**.md'
      - 'samples/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'samples/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run all tests
        run: ./gradlew check --stacktrace --info
        shell: bash

  assemble:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run assemble
        run: ./gradlew assemble --stacktrace
        shell: bash

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Run format check
        run: ./gradlew ktlintCheck --stacktrace
        shell: bash
